services:

  wordpress:
    image: wordpress
    ports:
      - 8070:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: tcdev
      WORDPRESS_DB_PASSWORD: tcdev
      WORDPRESS_DB_NAME: mamonas_site_orders
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mamonas_site_orders
      MYSQL_USER: tcdev
      MYSQL_PASSWORD: tcdev
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql  # Agora os dados do banco ficarão na pasta 'mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: tcdev
    depends_on:
      - db
